apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cuzkh6zqw-dotnet-basic
  janus-idp.io/tekton: cuzkh6zqw-dotnet-basic
  backstage.io/kubernetes-id: cuzkh6zqw-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cuzkh6zqw-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
